"""
ROI Tracker
Real-time ROI calculation and tracking system
"""

from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import logging

logger = logging.getLogger(__name__)


class ROIMetricType(Enum):
    """Types of ROI metrics"""
    NICHE_ROI = "niche_roi"
    AGENT_ROI = "agent_roi"
    COMMITTEE_ROI = "committee_roi"
    SYSTEM_ROI = "system_roi"


@dataclass
class ROIMetric:
    """Individual ROI metric"""
    metric_id: str
    entity_id: str  # ID of niche, agent, committee, or "system"
    entity_type: ROIMetricType
    revenue: float
    costs: float
    roi: float  # (revenue - costs) / costs
    roi_percentage: float
    period_start: str
    period_end: str
    calculated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class PerformanceSnapshot:
    """Performance snapshot for an entity"""
    entity_id: str
    entity_name: str
    entity_type: str
    current_roi: float
    total_revenue: float
    total_costs: float
    actions_taken: int
    success_rate: float
    trend: str  # improving, stable, declining
    last_updated: str = field(default_factory=lambda: datetime.utcnow().isoformat())


class ROITracker:
    """
    Tracks ROI at multiple levels:
    - Per niche
    - Per agent
    - Per committee
    - System-wide
    
    Calculates: ROI = (Revenue - Costs) / Costs
    """
    
    def __init__(self):
        self.metrics: List[ROIMetric] = []
        self.niche_metrics: Dict[str, List[ROIMetric]] = {}
        self.agent_metrics: Dict[str, List[ROIMetric]] = {}
        self.committee_metrics: Dict[str, List[ROIMetric]] = {}
        self.system_metrics: List[ROIMetric] = []
        
        logger.info("📊 ROI Tracker initialized")
    
    def calculate_niche_roi(
        self,
        niche_id: str,
        niche_name: str,
        revenue: float,
        costs: float,
        period_days: int = 30
    ) -> ROIMetric:
        """
        Calculate ROI for a specific niche
        
        Args:
            niche_id: Niche identifier
            niche_name: Niche name
            revenue: Revenue generated
            costs: Costs incurred
            period_days: Period length
            
        Returns:
            ROIMetric object
        """
        period_end = datetime.utcnow()
        period_start = period_end - timedelta(days=period_days)
        
        roi = (revenue - costs) / costs if costs > 0 else 0
        roi_percentage = roi * 100
        
        metric = ROIMetric(
            metric_id=f"ROI-NICHE-{niche_id}-{datetime.utcnow().strftime('%Y%m%d')}",
            entity_id=niche_id,
            entity_type=ROIMetricType.NICHE_ROI,
            revenue=revenue,
            costs=costs,
            roi=roi,
            roi_percentage=roi_percentage,
            period_start=period_start.isoformat(),
            period_end=period_end.isoformat()
        )
        
        self.metrics.append(metric)
        
        if niche_id not in self.niche_metrics:
            self.niche_metrics[niche_id] = []
        self.niche_metrics[niche_id].append(metric)
        
        logger.info(
            f"💰 Niche ROI calculated: {niche_name} = {roi_percentage:.1f}% "
            f"(${revenue:.2f} revenue, ${costs:.2f} costs)"
        )
        
        return metric
    
    def calculate_agent_roi(
        self,
        agent_id: str,
        agent_name: str,
        revenue: float,
        costs: float,
        period_days: int = 30
    ) -> ROIMetric:
        """
        Calculate ROI for a specific agent
        
        Args:
            agent_id: Agent identifier
            agent_name: Agent name
            revenue: Revenue generated by agent
            costs: Costs incurred by agent (compute, etc.)
            period_days: Period length
            
        Returns:
            ROIMetric object
        """
        period_end = datetime.utcnow()
        period_start = period_end - timedelta(days=period_days)
        
        roi = (revenue - costs) / costs if costs > 0 else 0
        roi_percentage = roi * 100
        
        metric = ROIMetric(
            metric_id=f"ROI-AGENT-{agent_id}-{datetime.utcnow().strftime('%Y%m%d')}",
            entity_id=agent_id,
            entity_type=ROIMetricType.AGENT_ROI,
            revenue=revenue,
            costs=costs,
            roi=roi,
            roi_percentage=roi_percentage,
            period_start=period_start.isoformat(),
            period_end=period_end.isoformat()
        )
        
        self.metrics.append(metric)
        
        if agent_id not in self.agent_metrics:
            self.agent_metrics[agent_id] = []
        self.agent_metrics[agent_id].append(metric)
        
        logger.info(
            f"🤖 Agent ROI calculated: {agent_name} = {roi_percentage:.1f}%"
        )
        
        return metric
    
    def calculate_committee_roi(
        self,
        committee_id: str,
        committee_name: str,
        revenue: float,
        costs: float,
        period_days: int = 30
    ) -> ROIMetric:
        """
        Calculate ROI for a committee
        
        Args:
            committee_id: Committee identifier
            committee_name: Committee name
            revenue: Revenue attributed to committee decisions
            costs: Committee operating costs
            period_days: Period length
            
        Returns:
            ROIMetric object
        """
        period_end = datetime.utcnow()
        period_start = period_end - timedelta(days=period_days)
        
        roi = (revenue - costs) / costs if costs > 0 else 0
        roi_percentage = roi * 100
        
        metric = ROIMetric(
            metric_id=f"ROI-COMMITTEE-{committee_id}-{datetime.utcnow().strftime('%Y%m%d')}",
            entity_id=committee_id,
            entity_type=ROIMetricType.COMMITTEE_ROI,
            revenue=revenue,
            costs=costs,
            roi=roi,
            roi_percentage=roi_percentage,
            period_start=period_start.isoformat(),
            period_end=period_end.isoformat()
        )
        
        self.metrics.append(metric)
        
        if committee_id not in self.committee_metrics:
            self.committee_metrics[committee_id] = []
        self.committee_metrics[committee_id].append(metric)
        
        logger.info(
            f"🏛️ Committee ROI calculated: {committee_name} = {roi_percentage:.1f}%"
        )
        
        return metric
    
    def calculate_system_roi(
        self,
        total_revenue: float,
        total_costs: float,
        period_days: int = 30
    ) -> ROIMetric:
        """
        Calculate system-wide ROI
        
        Args:
            total_revenue: Total system revenue
            total_costs: Total system costs
            period_days: Period length
            
        Returns:
            ROIMetric object
        """
        period_end = datetime.utcnow()
        period_start = period_end - timedelta(days=period_days)
        
        roi = (total_revenue - total_costs) / total_costs if total_costs > 0 else 0
        roi_percentage = roi * 100
        
        metric = ROIMetric(
            metric_id=f"ROI-SYSTEM-{datetime.utcnow().strftime('%Y%m%d')}",
            entity_id="system",
            entity_type=ROIMetricType.SYSTEM_ROI,
            revenue=total_revenue,
            costs=total_costs,
            roi=roi,
            roi_percentage=roi_percentage,
            period_start=period_start.isoformat(),
            period_end=period_end.isoformat()
        )
        
        self.metrics.append(metric)
        self.system_metrics.append(metric)
        
        logger.info(
            f"🌐 System ROI calculated: {roi_percentage:.1f}% "
            f"(${total_revenue:.2f} revenue, ${total_costs:.2f} costs)"
        )
        
        return metric
    
    def get_niche_roi_history(self, niche_id: str, limit: int = 30) -> List[ROIMetric]:
        """Get ROI history for a niche"""
        metrics = self.niche_metrics.get(niche_id, [])
        return sorted(metrics, key=lambda m: m.calculated_at, reverse=True)[:limit]
    
    def get_agent_roi_history(self, agent_id: str, limit: int = 30) -> List[ROIMetric]:
        """Get ROI history for an agent"""
        metrics = self.agent_metrics.get(agent_id, [])
        return sorted(metrics, key=lambda m: m.calculated_at, reverse=True)[:limit]
    
    def get_committee_roi_history(self, committee_id: str, limit: int = 30) -> List[ROIMetric]:
        """Get ROI history for a committee"""
        metrics = self.committee_metrics.get(committee_id, [])
        return sorted(metrics, key=lambda m: m.calculated_at, reverse=True)[:limit]
    
    def get_system_roi_history(self, limit: int = 30) -> List[ROIMetric]:
        """Get system-wide ROI history"""
        return sorted(self.system_metrics, key=lambda m: m.calculated_at, reverse=True)[:limit]
    
    def get_top_performing_niches(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top performing niches by ROI"""
        latest_metrics = {}
        
        for niche_id, metrics in self.niche_metrics.items():
            if metrics:
                latest = max(metrics, key=lambda m: m.calculated_at)
                latest_metrics[niche_id] = latest
        
        sorted_niches = sorted(
            latest_metrics.values(),
            key=lambda m: m.roi_percentage,
            reverse=True
        )
        
        return [
            {
                "niche_id": m.entity_id,
                "roi_percentage": m.roi_percentage,
                "revenue": m.revenue,
                "costs": m.costs,
                "calculated_at": m.calculated_at
            }
            for m in sorted_niches[:limit]
        ]
    
    def get_top_performing_agents(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get top performing agents by ROI"""
        latest_metrics = {}
        
        for agent_id, metrics in self.agent_metrics.items():
            if metrics:
                latest = max(metrics, key=lambda m: m.calculated_at)
                latest_metrics[agent_id] = latest
        
        sorted_agents = sorted(
            latest_metrics.values(),
            key=lambda m: m.roi_percentage,
            reverse=True
        )
        
        return [
            {
                "agent_id": m.entity_id,
                "roi_percentage": m.roi_percentage,
                "revenue": m.revenue,
                "costs": m.costs,
                "calculated_at": m.calculated_at
            }
            for m in sorted_agents[:limit]
        ]
    
    def get_roi_summary(self) -> Dict[str, Any]:
        """Get comprehensive ROI summary"""
        # Latest system ROI
        latest_system_roi = self.system_metrics[-1] if self.system_metrics else None
        
        # Count entities being tracked
        total_niches = len(self.niche_metrics)
        total_agents = len(self.agent_metrics)
        total_committees = len(self.committee_metrics)
        
        # Calculate averages
        avg_niche_roi = 0
        if self.niche_metrics:
            latest_niche_rois = [
                max(metrics, key=lambda m: m.calculated_at).roi_percentage
                for metrics in self.niche_metrics.values()
                if metrics
            ]
            avg_niche_roi = sum(latest_niche_rois) / len(latest_niche_rois) if latest_niche_rois else 0
        
        avg_agent_roi = 0
        if self.agent_metrics:
            latest_agent_rois = [
                max(metrics, key=lambda m: m.calculated_at).roi_percentage
                for metrics in self.agent_metrics.values()
                if metrics
            ]
            avg_agent_roi = sum(latest_agent_rois) / len(latest_agent_rois) if latest_agent_rois else 0
        
        return {
            "system_roi": {
                "roi_percentage": latest_system_roi.roi_percentage if latest_system_roi else 0,
                "revenue": latest_system_roi.revenue if latest_system_roi else 0,
                "costs": latest_system_roi.costs if latest_system_roi else 0,
                "last_updated": latest_system_roi.calculated_at if latest_system_roi else None
            },
            "tracking": {
                "niches": total_niches,
                "agents": total_agents,
                "committees": total_committees,
                "total_metrics": len(self.metrics)
            },
            "averages": {
                "niche_roi": avg_niche_roi,
                "agent_roi": avg_agent_roi
            },
            "top_performers": {
                "niches": self.get_top_performing_niches(5),
                "agents": self.get_top_performing_agents(5)
            }
        }


# Example Usage
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    # Initialize tracker
    tracker = ROITracker()
    
    # Calculate niche ROI
    niche_roi = tracker.calculate_niche_roi(
        niche_id="AI-TOOLS-001",
        niche_name="AI Productivity Tools",
        revenue=500.0,
        costs=50.0,
        period_days=30
    )
    
    print(f"\n💰 Niche ROI: {niche_roi.roi_percentage:.1f}%")
    
    # Calculate agent ROI
    agent_roi = tracker.calculate_agent_roi(
        agent_id="agent-123",
        agent_name="Content Generator",
        revenue=200.0,
        costs=10.0,
        period_days=30
    )
    
    print(f"🤖 Agent ROI: {agent_roi.roi_percentage:.1f}%")
    
    # Calculate system ROI
    system_roi = tracker.calculate_system_roi(
        total_revenue=1000.0,
        total_costs=100.0,
        period_days=30
    )
    
    print(f"🌐 System ROI: {system_roi.roi_percentage:.1f}%")
    
    # Get summary
    summary = tracker.get_roi_summary()
    print(f"\n📊 ROI Summary:")
    print(f"   System ROI: {summary['system_roi']['roi_percentage']:.1f}%")
    print(f"   Tracking {summary['tracking']['niches']} niches")
    print(f"   Average Niche ROI: {summary['averages']['niche_roi']:.1f}%")
